tracer:
  property: "I AM THE DEFAULT"
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://database:5432/eagle_eye_local
    username: postgres
    password: "{cipher}3008767880a73cf550e418e995d983394b0a0b5d1c7ec41123ee071d20861bf7"
    testWhileIdle: true
    validationQuery: SELECT 1
  database:
    driverClassName: org.postgresql.Driver
example:
  property: "I AM THE DEFAULT EXAMPLE PROPERTY"
